### ISSUE TITLE
Skype fails to start after installing it via boxen

### ISSUE THREAD

**Issue by imdhmd** [boxen/puppet-skype#19]
When i try to start the skype console exec manually, this is the error i see in the terminal: `Check 2 failed. Can't run Skype`

**Comment by jacobbednarz** [comment]
Deprecated in favour of [brewcask][1] and [Boxen's in built support for
homebrew/brewcask][2].

[1]: https://caskroom.github.io/
[2]: https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17
